apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentregistry.fullname" . }}-config
  labels:
    {{- include "agentregistry.labels" . | nindent 4 }}
  {{- $annotations := include "agentregistry.annotations" (dict "annotations" dict "context" $) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
data:
  AGENT_REGISTRY_SERVER_ADDRESS: {{ .Values.config.serverAddress | quote }}
  AGENT_REGISTRY_STORAGE_DIR: {{ .Values.config.storageDir | quote }}
  AGENT_REGISTRY_AGENT_GATEWAY_PORT: {{ .Values.config.agentGatewayPort | quote }}
  AGENT_REGISTRY_MCP_PORT: {{ .Values.config.agentRegistryMcpPort | quote }}
  AGENT_REGISTRY_ENABLE_REGISTRY_VALIDATION: {{ .Values.config.enableRegistryValidation | quote }}
  AGENT_REGISTRY_DISABLE_BUILTIN_SEED: {{ .Values.config.disableBuiltinSeed | quote }}
  {{- if .Values.config.seedFrom }}
  AGENT_REGISTRY_SEED_FROM: {{ .Values.config.seedFrom | quote }}
  {{- end }}
