{{- if .Values.database.postgres.bundled.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentregistry.fullname" . }}-postgresql
  labels:
    {{- include "agentregistry.postgresql.labels" . | nindent 4 }}
  {{- $annotations := include "agentregistry.annotations" (dict "annotations" dict "context" $) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ "agentregistry" | b64enc | quote }}
{{- end }}
