{{- $needJwtKey := not .Values.config.existingSecret -}}
{{- if $needJwtKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentregistry.fullname" . }}
  labels:
    {{- include "agentregistry.labels" . | nindent 4 }}
  {{- $annotations := include "agentregistry.annotations" (dict "annotations" dict "context" $) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  AGENT_REGISTRY_JWT_PRIVATE_KEY: {{ .Values.config.jwtPrivateKey | toString | b64enc | quote }}
{{- end }}
