{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentregistry.serviceAccountName" . }}
  labels:
    {{- include "agentregistry.labels" . | nindent 4 }}
  {{- $annotations := include "agentregistry.annotations" (dict "annotations" .Values.serviceAccount.annotations "context" $) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
